'use client';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight,FileText,CalendarDays,Trophy} from 'lucide-react';
import type {Entry} from '@/lib/acervo';
import ScrollReveal from './react-bits/ScrollReveal';
import Magnet from './react-bits/Magnet';
import Currents from './currents';
const formatDate=(d:string)=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(d.slice(0,10)+'T12:00:00Z'));
const INSTAGRAM_WIDGET_SRC=process.env.NEXT_PUBLIC_INSTAGRAM_WIDGET_SRC||'';
const INSTAGRAM_PROFILE_URL=process.env.NEXT_PUBLIC_INSTAGRAM_PROFILE_URL||'';
export default function HomeSections({news,events,latest}:{news:Entry[];events:Entry[];latest:Entry[]}){
 return <>
 <div className="values-strip"><span>ESPORTE</span><i/><span>PERTENCIMENTO</span><i/><span>SUPERAÇÃO</span><i/><span>RIO GRANDE DO SUL</span></div>
 <section id="noticias" className="section news-section"><div className="section-label"><span>02 / DA ÁGUA PARA A HISTÓRIA</span><span>NOTÍCIAS & CONQUISTAS</span></div><div className="section-heading"><ScrollReveal>O que move a nossa canoagem.</ScrollReveal><Link className="text-link" href="/acervo?categoria=noticias">Todas as publicações <ArrowUpRight size={18}/></Link></div><div className="news-grid">{news.map((n,i)=><Link href={'/acervo/'+n.slug} className={'news-card '+(i===0?'news-featured':'')} key={n.id} data-reveal><div className="news-image"><img src={n.image} alt="" width="1024" height="768" loading="lazy"/><span className="image-tag">{(n.categories[0]||'Notícias').toUpperCase()}</span><span className="news-arrow"><ArrowUpRight size={22}/></span></div><div className="news-copy"><time dateTime={n.date}>{formatDate(n.date)}</time><h3>{n.title}</h3>{i===0&&<p>{n.excerpt.replace(/\[.*?\]/g,'').trim()}</p>}</div></Link>)}</div><div className="latest-list"><span className="eyebrow">ÚLTIMAS PUBLICAÇÕES</span>{latest.map(n=><Link href={'/acervo/'+n.slug} key={n.id}><time dateTime={n.date}>{formatDate(n.date)}</time><span>{n.title}</span><ArrowUpRight size={17}/></Link>)}</div></section>
 <section id="competicoes" className="section competition-section"><div className="section-label"><span>03 / NA RAIA</span><span>COMPETIÇÕES & RESULTADOS</span></div><div className="competition-grid"><div className="competition-copy"><ScrollReveal>Cada largada. Uma nova história.</ScrollReveal><p>Encontre os comunicados das provas, consulte regulamentos e acompanhe os resultados da canoagem gaúcha.</p><Link className="button button-yellow" href="/acervo?categoria=calendario">Consultar calendário <CalendarDays size={19}/></Link><Link className="text-link light" href="/acervo?categoria=resultados">Resultados e rankings <Trophy size={19}/></Link></div><div className="race-list"><span className="eyebrow race-heading">DO ARQUIVO DE COMPETIÇÕES</span>{events.map((n,i)=><Link className="race-row" href={'/acervo/'+n.slug} key={n.id} data-reveal><span className="race-index">0{i+1}</span><div><span className="race-date">PUBLICADO EM {formatDate(n.date).toUpperCase()}</span><h3>{n.title}</h3><span className="race-link">Informações da edição <ArrowRight size={15}/></span></div><ArrowUpRight size={24}/></Link>)}<p className="archive-note">Edições históricas. Consulte o calendário e os comunicados para confirmar novas datas.</p></div></div></section>
 <section className="section archive-section"><div className="section-label"><span>04 / MEMÓRIA & TRANSPARÊNCIA</span><span>O ESPORTE TAMBÉM SE CONSTRÓI AQUI</span></div><div className="section-heading"><ScrollReveal>Nossa história. Um acervo de todos.</ScrollReveal><p>Documentos, decisões e resultados.<br/>A informação que conecta a Federação<br/>a quem faz parte dela.</p></div><div className="document-grid">{[{n:'01',title:'Governança',copy:'Diretoria, balanços e documentos institucionais.',url:'/acervo?categoria=governanca'},{n:'02',title:'Circulares e editais',copy:'Comunicados e convocações da Federação.',url:'/acervo?categoria=circulares'},{n:'03',title:'Regulamentos',copy:'Regras e documentos das competições.',url:'/acervo?categoria=regulamento'}].map(d=><Link href={d.url} key={d.n} className="document-card" data-reveal><div><span>{d.n}</span><FileText size={24} strokeWidth={1.3}/></div><h3>{d.title}</h3><p>{d.copy}</p><span className="document-action">Consultar documentos <ArrowUpRight size={19}/></span></Link>)}</div><Link className="text-link archive-all" href="/acervo">Explorar todo o acervo <ArrowUpRight size={18}/></Link></section>
 {(INSTAGRAM_WIDGET_SRC||INSTAGRAM_PROFILE_URL)&&<section className="section instagram-section"><div className="section-label"><span>05 / NAS REDES</span><span>SIGA A FGC NO INSTAGRAM</span></div>{INSTAGRAM_WIDGET_SRC?<div className="instagram-embed"><iframe src={INSTAGRAM_WIDGET_SRC} title="Publicações do Instagram da FGC" loading="lazy" scrolling="no"/></div>:<a className="text-link" href={INSTAGRAM_PROFILE_URL} target="_blank" rel="noopener noreferrer">Siga a FGC no Instagram <ArrowUpRight size={18}/></a>}</section>}
 <section id="federado" className="join-section"><div className="join-image"><img src="/velocidade-vertical.webp" alt="Aplicação da marca FGC em equipamentos de canoagem velocidade" loading="lazy" width="900" height="1200"/><div className="join-image-caption"><span>O PRÓXIMO CAPÍTULO</span><strong>PODE SER O SEU.</strong></div></div><div className="join-content"><Currents/><div className="join-inner"><span className="eyebrow light">06 / FAÇA PARTE</span><ScrollReveal>Seja um federado!</ScrollReveal><p>A sua remada faz parte de algo maior.<br/>Dê o próximo passo e conecte-se à comunidade da canoagem.</p><Magnet><a className="button button-yellow" href="https://sge.cbca.org.br/cadastroExterno/atleta" target="_blank" rel="noopener noreferrer">Quero me federar <ArrowUpRight size={20}/></a></Magnet><span className="external-note">Você será direcionado ao cadastro de atleta da CBCa.</span><div className="join-help"><Link href="/acervo/atleta">Orientações para atletas <ArrowRight size={17}/></Link><Link href="/acervo/instrucao-para-cadastro">Representa um clube? <ArrowRight size={17}/></Link></div></div></div></section>
 </>;
}
