'use client';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight,FileText,CalendarDays,Trophy} from 'lucide-react';
import type {Entry} from '@/lib/acervo';
import ScrollReveal from './react-bits/ScrollReveal';
import Magnet from './react-bits/Magnet';
import Currents from './currents';
import {INSTAGRAM_URL,INSTAGRAM_HANDLE} from '@/lib/site';
const formatDate=(d:string)=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(d.slice(0,10)+'T12:00:00Z'));
const INSTAGRAM_WIDGET_SRC=process.env.NEXT_PUBLIC_INSTAGRAM_WIDGET_SRC||'';
const docCount=(n:number)=>`${n} ${n===1?'documento':'documentos'}`;
export type DocCounts={governanca:number;circulares:number;regulamento:number};
export default function HomeSections({news,results,latest,docCounts}:{news:Entry[];results:Entry[];latest:Entry[];docCounts:DocCounts}){
 return <>
 <div className="values-strip"><span>ESPORTE</span><i/><span>PERTENCIMENTO</span><i/><span>SUPERAÇÃO</span><i/><span>RIO GRANDE DO SUL</span></div>
 <section id="noticias" className="section news-section"><div className="section-label"><span>DA ÁGUA PARA A HISTÓRIA</span><span>NOTÍCIAS & CONQUISTAS</span></div><div className="section-heading"><ScrollReveal>O que move a nossa canoagem.</ScrollReveal><Link className="text-link" href="/acervo?categoria=noticias">Todas as publicações <ArrowUpRight size={18}/></Link></div><div className="news-grid">{news.map((n,i)=><Link href={'/acervo/'+n.slug} className={'news-card '+(i===0?'news-featured':'')} key={n.id} data-reveal><div className="news-image"><img src={n.image} alt="" width="1024" height="768" loading="lazy"/><span className="image-tag">{(n.categories[0]||'Notícias').toUpperCase()}</span><span className="news-arrow"><ArrowUpRight size={22}/></span></div><div className="news-copy"><time dateTime={n.date}>{formatDate(n.date)}</time><h3>{n.title}</h3>{i===0&&<p>{n.excerpt.replace(/\[.*?\]/g,'').trim()}</p>}</div></Link>)}</div><div className="latest-list"><span className="eyebrow">ÚLTIMAS PUBLICAÇÕES</span>{latest.map(n=><Link href={'/acervo/'+n.slug} key={n.id}><time dateTime={n.date}>{formatDate(n.date)}</time><span>{n.title}</span><ArrowUpRight size={17}/></Link>)}</div></section>
 <section id="competicoes" className="section competition-section"><div className="section-label"><span>NA RAIA</span><span>COMPETIÇÕES & RESULTADOS</span></div><div className="competition-grid"><div className="competition-copy"><ScrollReveal>Cada largada. Uma nova história.</ScrollReveal><p>Encontre os comunicados das provas, consulte regulamentos e acompanhe os resultados da canoagem gaúcha.</p><a className="button button-yellow" href="#calendario">Consultar calendário <CalendarDays size={19}/></a><Link className="text-link light" href="/acervo?categoria=resultados">Resultados e rankings <Trophy size={19}/></Link></div><div className="race-list"><span className="eyebrow race-heading">ÚLTIMOS RESULTADOS</span>{results.map(n=><Link className="race-row" href={'/acervo/'+n.slug} key={n.id} data-reveal><span className="race-index">{n.date.slice(0,4)}</span><div><span className="race-date">PUBLICADO EM {formatDate(n.date).toUpperCase()}</span><h3>{n.title}</h3><span className="race-link">Ver resultado <ArrowRight size={15}/></span></div><ArrowUpRight size={24}/></Link>)}</div></div></section>
 <section className="section archive-section"><div className="section-label"><span>MEMÓRIA & TRANSPARÊNCIA</span><span>O ESPORTE TAMBÉM SE CONSTRÓI AQUI</span></div><div className="section-heading"><ScrollReveal>Nossa história. Um acervo de todos.</ScrollReveal><p>Documentos, decisões e resultados.<br/>A informação que conecta a Federação<br/>a quem faz parte dela.</p></div><div className="document-grid">{[{n:docCounts.governanca,title:'Governança',copy:'Diretoria, balanços e documentos institucionais.',url:'/acervo?categoria=governanca'},{n:docCounts.circulares,title:'Circulares e editais',copy:'Comunicados e convocações da Federação.',url:'/acervo?categoria=circulares'},{n:docCounts.regulamento,title:'Regulamentos',copy:'Regras e documentos das competições.',url:'/acervo?categoria=regulamento'}].map(d=><Link href={d.url} key={d.url} className="document-card" data-reveal><div><span>{docCount(d.n)}</span><FileText size={24} strokeWidth={1.3}/></div><h3>{d.title}</h3><p>{d.copy}</p><span className="document-action">Consultar documentos <ArrowUpRight size={19}/></span></Link>)}</div><Link className="text-link archive-all" href="/acervo">Explorar todo o acervo <ArrowUpRight size={18}/></Link></section>
 <section className="section instagram-section"><div className="section-label"><span>NAS REDES</span><span>ACOMPANHE A CANOAGEM GAÚCHA</span></div><div className="section-heading"><ScrollReveal>Da raia para o seu feed.</ScrollReveal><p>Acompanhe as novidades<br/>da canoagem gaúcha no Instagram.</p></div>{INSTAGRAM_WIDGET_SRC&&<div className="instagram-embed"><iframe src={INSTAGRAM_WIDGET_SRC} title={`Publicações do Instagram ${INSTAGRAM_HANDLE}`} loading="lazy" scrolling="no"/></div>}<a className="instagram-profile" href={INSTAGRAM_URL} target="_blank" rel="noopener noreferrer" data-reveal><div><span className="eyebrow">NO INSTAGRAM</span><strong>{INSTAGRAM_HANDLE}</strong></div><span className="button button-navy">Seguir no Instagram <ArrowUpRight size={19}/></span></a></section>
 <section id="federado" className="join-section"><div className="join-image"><img src="/images/federado-atleta.webp" alt="Jovem atleta comemorando no caiaque, ao lado do parceiro de equipe" loading="lazy" width="960" height="1200"/><div className="join-image-caption"><span>O PRÓXIMO CAPÍTULO</span><strong>PODE SER O SEU.</strong></div></div><div className="join-content"><Currents/><div className="join-inner"><span className="eyebrow light">FAÇA PARTE</span><ScrollReveal>Seja um federado!</ScrollReveal><p>A sua remada faz parte de algo maior.<br/>Dê o próximo passo e conecte-se à comunidade da canoagem.</p><Magnet><a className="button button-yellow" href="https://sge.cbca.org.br/cadastroExterno/atleta" target="_blank" rel="noopener noreferrer">Quero me federar <ArrowUpRight size={20}/></a></Magnet><span className="external-note">Você será direcionado ao cadastro de atleta da CBCa.</span><div className="join-help"><Link href="/acervo/atleta">Orientações para atletas <ArrowRight size={17}/></Link><Link href="/acervo/instrucao-para-cadastro">Representa um clube? <ArrowRight size={17}/></Link></div></div></div></section>
 </>;
}
